YelpScrape/YelpScrapeWeb/Controllers/BusinessesController.cs
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using System.Web;
using YelpScrapeWeb.Models.YelpGraphQLBusinesses;

namespace YelpScrapeWeb.Controllers
{
    public class BusinessesController : Controller
    {
        private readonly ISearchBusinessesConsumer _searchBusinessesConsumer;
        private readonly ISearchBusinessesResultsConsumer _searchBusinessesResultsConsumer;

        public BusinessesController(ISearchBusinessesConsumer searchBusinessesConsumer, ISearchBusinessesResultsConsumer searchBusinessesResultsConsumer)
        {
            _searchBusinessesConsumer = searchBusinessesConsumer;
            _searchBusinessesResultsConsumer = searchBusinessesResultsConsumer;
        }

        public IActionResult Search()
        {
            return View();
        }

        [HttpPost]
        // SearchBusiness
        public async Task<IActionResult> Search(SearchBusinessesArguments searchBusinessesArguments)
        {
            if (!this.ModelState.IsValid)
            {
                return View();
            }

            return RedirectToAction("GetBusinesses", searchBusinessesArguments);
        }

        [HttpGet]
        public async Task<IActionResult> GetBusinesses(SearchBusinessesArguments searchBusinessesArguments, int offset)
        {
            var searchBusinessesObj = await _searchBusinessesConsumer.GetAllBusinesses(searchBusinessesArguments, offset);
            var businesses = searchBusinessesObj.Businesses;
            var total = searchBusinessesObj.Total;
            var searchResultsObj = _searchBusinessesResultsConsumer.CreateSearchResults(searchBusinessesArguments, businesses, total);

            return View(searchResultsObj);
        }
    }
}

YelpScrape/YelpScrapeWeb/Controllers/ReviewsController.cs
using Microsoft.AspNetCore.Mvc;
using YelpScrapeWeb.Models.YelpGraphQLReviews;

namespace YelpScrapeWeb.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly ISearchReviewsConsumer _searchReviewsConsumer;
        private readonly ISearchReviewsResultsConsumer _searchReviewsResultsConsumer;

        public ReviewsController(ISearchReviewsConsumer searchReviewsConsumer, ISearchReviewsResultsConsumer searchReviewsResultsConsumer)
        {
            _searchReviewsConsumer = searchReviewsConsumer;
            _searchReviewsResultsConsumer = searchReviewsResultsConsumer;
        }

        public IActionResult Search()
        {
            return View();
        }

        [HttpPost]
        // SearchReviews
        public async Task<IActionResult> Search(SearchReviewsArguments searchReviewsArguments)
        {
            if (!this.ModelState.IsValid)
            {
                return View();
            }

            var reviews = await _searchReviewsConsumer.GetAllReviews(searchReviewsArguments);
            var searchResultsObj = _searchReviewsResultsConsumer.CreateSearchResults(searchReviewsArguments, reviews);

            return View(searchResultsObj);
        }
    }
}

YelpScrape/YelpScrapeWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - YelpScrapeWeb</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @*<link rel="stylesheet" href="~/YelpScrapeWeb.styles.css" asp-append-version="true" />*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
          <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">YelpScrapeWeb</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
              <ul class="navbar-nav me-auto">
                <li class="nav-item">
                  <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">Home
                    <span class="visually-hidden">(current)</span>
                  </a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">GraphQL</a>
                  <div class="dropdown-menu">
                    <a class="dropdown-item" asp-area="" asp-controller="Businesses" asp-action="Search">Search Businesses</a>
                    <a class="dropdown-item" asp-area="" asp-controller="Reviews" asp-action="Search">Search Reviews</a>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container" style="position:absolute; bottom:1em">
            &copy; 2022 - YelpScrapeWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>